
# DiscordMc by Norbit4
# Ver 1.0.1

#---------------------------------------#
#             [bot config]              #
#---------------------------------------#

enable: false
command-prefix: 'dc'
token: ''
bot-activity: ''

# database mongodb
host: ''
port: 27017
user: ''
password: ''
database: ''
ssl: false

#---------------------------------------#
#              [Messages]               #
#---------------------------------------#

# discord embeds colors
warn-message-tittle: 'WARN'
warn-message-rgb:
  #R
  - 213
  #G
  - 156
  #B
  - 71

success-message-tittle: 'SUCCESS'
success-message-rgb:
  - 26
  - 154
  - 74

error-message-tittle: 'ERROR'
error-message-rgb:
  - 194
  - 50
  - 50

#discord messages
player-is-sync: 'This player is sync!'
offline-player: 'This player is offline!'
sync-info: 'Type /sync in minecraft chat to sync your accounts'
sync-success: '{PLAYER} with {DISCORD}'

#minecraft messages
sync-info-mc: '&7Type &8/&bsync &7to connect your account with&a {DISCORD}'
sync-success-mc: '&aSuccess syc with {DISCORD}'
sync-time-out: '&7Time out!'

#---------------------------------------#
#         [discord-chat-module]         #
#---------------------------------------#

discord-chat-module: false
channel-name: ''

# minecraft server chat
discord-prefix: '&d[DC] '
mc-prefix: '&a[MC] '
message-mark: '&7: '
message-color: '&7'
nick-color: '&f'

# discord channel chat
discord-message-mark: ': '

# embeds chat colors
discord-user-rgb:
  - 142
  - 87
  - 178

mc-user-rgb:
  - 33
  - 241
  - 99