# ------------------------------------------------------------------------#
#    _____    _                                   _   __  __    _____     #
#   |  __ \  (_)                                 | | |  \/  |  / ____|    #
#   | |  | |  _   ___    ___    ___    _ __    __| | | \  / | | |         #
#   | |  | | | | / __|  / __|  / _ \  | '__|  / _` | | |\/| | | |         #
#   | |__| | | | \__ \ | (__  | (_) | | |    | (_| | | |  | | | |____     #
#   |_____/  |_| |___/  \___|  \___/  |_|     \__,_| |_|  |_|  \_____|    #
#                                                                         #
# ------------------------------------------------------------------------#

# DiscordMc by Norbit4

# github: https://github.com/Norbit4
# website https://norbit.fun/

# If you like the plugin, support me with a positive opinion on spigot.org, thanks! <3

#---------------------------------------#
#             [Bot config]              #
#---------------------------------------#

# configuration: https://github.com/Norbit4/DiscordMc/wiki/Configuration
enable: false
bot-token: ''
bot-activity: ''
discord-server-id: ''

#commands prefix
prefix-command: 'discordmc'
sync-command-arg: 'sync'
sync-command-clear-arg: 'syncclear'
rank-reload-command-arg: 'rankreload'

# types: local/mysql/mongodb
# with a large number of players on the server (100+), I recommend not using a local database, use mysql or mongodb
database-type: 'local'
host: ''
port: 3306
user: ''
password: ''
database: ''
ssl: false

#---------------------------------------#
#            [Sync profiles]            #
#---------------------------------------#

embed-profile-title: 'Profile'
embed-profile-rgb:
  - 154
  - 199
  - 50

# to use placeholders you need install PlaceholderAPI https://www.spigotmc.org/resources/placeholderapi.6245/
# placeholders https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#player
# to download player placeholders: /papi ecloud download Player

embed-profile-online:
  # 'TITLE//DESC'
  - 'nick:// %player_name%'
  - 'status:// Online'
  - 'world:// %player_world%'
  - 'loc:// X: %player_x% Y: %player_y% Z: %player_z%'

embed-profile-offline:
  # 'TITLE//DESC'
  - 'nick:// %player_name%'
  - 'status:// Offline'

#---------------------------------------#
#          [Sync roles/perms]            #
#---------------------------------------#

# wiki sync: https://github.com/Norbit4/DiscordMc/wiki/Rank-sync

#---------------------------------------#
# [module-1] Sync minecraft perms to discord roles

sync-mc-permissions-enable: false

# discord name sync (set discord user mc name)
# this option need enabled 'sync-mc-permissions-enable'
# nick sync does not work for the discord server owner, it is specific to discord servers!
sync-name: false

# sync minecraft perms to discord roles
# this option need enabled 'sync-mc-permissions-enable'
# only top perm from minecraft will be synchronized with discord role (user can have only one role synced)
sync-mc-permissions:
  - 'rank-permission:discord-rank-id'

#---------------------------------------#
# [module-2] Sync discord roles to minecraft perms

sync-discord-roles-enable: false

# all roles from discord will be synchronized with minecraft perms
# this can be used to synchronize the users boosting the server and give them permissions for it on the server
# this option need enabled 'sync-discord-roles-enable'
sync-discord-roles:
  - 'rank-permission:discord-rank-id'

command-to-sync-permission: 'lp user {PLAYER} perm set {PERM}'
command-to-un-sync-permission: 'lp user {PLAYER} perm unset {PERM}'

#---------------------------------------#
#            [Sync commands]            #
#---------------------------------------#

# commands support PlaceholdersAPI
# commands to execute when the player syncs
execute-commands-on-sync: false
commands-on-sync:
  - 'lp user {PLAYER} perm set sync.true'
  - 'say Synced!'

# commands to execute when the player clears sync
execute-commands-on-sync-clear: false
commands-on-sync-clear:
  - 'lp user {PLAYER} perm unset sync.true'
  - 'say Synced clear!'

#---------------------------------------#
#              [Messages]               #
#---------------------------------------#

# discord embeds colors
warn-message-tittle: 'WARN'
warn-message-rgb:
  #R
  - 213
  #G
  - 156
  #B
  - 71

success-message-tittle: 'SUCCESS'
success-message-rgb:
  - 26
  - 154
  - 74

error-message-tittle: 'ERROR'
error-message-rgb:
  - 194
  - 50
  - 50

#discord messages
user-in-not-sync: 'You are not synchronized! Use **/sync** to sync your accounts!'
arg-user-in-not-sync: 'This user is not synchronized!'
player-is-sync: 'This player is synchronize!'
discord-user-is-sync: 'You are synchronized!'
offline-player: 'This player is offline!'
sync-info: 'Type **/{PREFIX} {ARG1}** in minecraft chat to sync your accounts!'
sync-success: 'The player **{PLAYER}** has been synchronized with **{DISCORD}** account!'

#minecraft messages
permission-message: '&cYou dont have permissions!'
sync-info-mc: '&7Type &8/&b{PREFIX} {ARG1} &7to connect your account with&a {DISCORD}'
sync-success-mc: '&aSuccess! &7The account has been synchronized with &c{DISCORD}!'
sync-clear-mc: '&aSuccess! &7The sync has been cleared!'
sync-time-out: '&7You dont have sync pending!'
player-is-not-sync: '&cYou are not sync!'
rank-reload-message: '&aSuccess! &7The rank has been reloaded!'

wrong-args-message: '&7Use: &8/&b{PREFIX} &a{ARG1} &8<&a{ARG2}&8>'

command-args-list:
  - '&7------------&8[{PREFIX}&8]------------'
  - ''
  - '&8/&b{PREFIX} &a{SYNC_CMD} &7- accept sync accounts'
  - '&8/&b{PREFIX} &a{SYNC_CLEAR_CMD} &7- clear your sync'
  - '&8/&b{PREFIX} &a{CHANNEL_CMD} &8<&a{CHANNEL_MC_ARG}/{CHANNEL_DC_ARG}&8> &7- change chat channel'
  - '&8/&b{PREFIX} &arankreload &7- reload synced rank'
  - '&8/&b{PREFIX} &areload &7- reload config.yml'
  - ''

#---------------------------------------#
#         [Discord-chat-module]         #
#---------------------------------------#

# help: https://github.com/Norbit4/DiscordMc/wiki/Chat-module

discord-chat-module: false
channel-chat-id: ''

# command
command-chat-change-arg: 'channel'
minecraft-chat-arg: 'mc'
discord-chat-arg: 'dc'
channel-change-message: '&7The channel has been changed to: &a{CHANNEL}'

# minecraft server chat
discord-prefix: '&d[DC] '
mc-prefix: '&a[MC] '
message-mark: '&7: '
message-color: '&7'
nick-color: '&f'

# discord channel chat
discord-message-mark: ': '

# embeds color
discord-user-rgb:
  - 142
  - 87
  - 178

mc-user-rgb:
  - 33
  - 241
  - 99

#---------------------------------------#
#        [Discord-console-module]       #
#---------------------------------------#

# help: https://github:com/Norbit4/DiscordMc/wiki/Cosole-module

discord-console-module: false
channel-console-id: ''

#allowed commands in discord console
discord-console-commands: true

#allowed to display info discord console
discord-console-display: true

#allow bots to use commands in discord console
discord-console-allow-bots: false

block-error-messages: false

# blocked commands in discord console
blocked-commands:
  - help
  - pl

#---------------------------------------#
#         [Discord-info-module]         #
#---------------------------------------#

# help: https://github.com/Norbit4/DiscordMc/wiki/Info-module

discord-info-module: false
channel-info-id: ''

# message info reload time in seconds, min time: 20s (for safe)
message-reload-time: 30

discord-info-rgb:
  - 26
  - 154
  - 74

# Placeholders:
# {SERVER_ONLINE}, {SERVER_MAX_PLAYERS}, {SERVER_TIME}, {SERVER_ALL_PLAYERS}, {SERVER_VERSION},
# {SERVER_ALLOW_NETHER}, {SERVER_ALLOW_END}

# PlaceholderAPI support: https://github.com/Norbit4/DiscordMc/wiki/PlaceholderApi-support
embed-tittle: ''
embed-desc: ''
embed-info:
  # 'TITLE//DESC'
  - 'Online://{SERVER_ONLINE}/{SERVER_MAX_PLAYERS}'
  - 'Up Time:// {SERVER_TIME}'
  - 'All Players:// {SERVER_ALL_PLAYERS}'
  - 'Ver:// {SERVER_VERSION}'
  - 'Nether:// {SERVER_ALLOW_NETHER}'
  - 'End:// {SERVER_ALLOW_END}'

false-info: 'false'
true-info: 'true'
# end