#---------------------------------------#
# DiscordMc by Norbit4
# ver 1.0.1
# github: https://github.com/Norbit4

#---------------------------------------#
#             [bot config]              #
#---------------------------------------#

enable: false
command-prefix: 'dc'
sync-command-arg: 'sync'
token: ''
bot-activity: ''
server-id: ''

# database mongodb
host: ''
port: 27017
user: ''
password: ''
database: ''
ssl: false

#---------------------------------------#
#              [Messages]               #
#---------------------------------------#

# discord embeds colors
warn-message-tittle: 'WARN'
warn-message-rgb:
  #R
  - 213
  #G
  - 156
  #B
  - 71

success-message-tittle: 'SUCCESS'
success-message-rgb:
  - 26
  - 154
  - 74

error-message-tittle: 'ERROR'
error-message-rgb:
  - 194
  - 50
  - 50

#discord messages
player-is-sync: 'This player is synchronize!'
offline-player: 'This player is offline!'
sync-info: 'Type **/{PREFIX} {ARG1}** in minecraft chat to sync your accounts!'
sync-success: 'The player {PLAYER} has been synchronized with {DISCORD} account!'

#minecraft messages
sync-info-mc: '&7Type &8/&b{PREFIX} {ARG1} &7to connect your account with&a {DISCORD}'
sync-success-mc: '&aSuccess! &7The account has been synchronized with &c{DISCORD}!'
sync-time-out: '&7You dont have sync pending!'

wrong-args-message: 'Use: /{PREFIX} {ARG1} {ARG2}'

command-args-list:
  - '&7------------&8[DC&8]------------'
  - ''
  - '&8/&bdc &8<&async&8>'
  - '&8/&bdc &8<s&ac&8> &8<&aglobal/discord&8>'
  - ''

#---------------------------------------#
#         [discord-chat-module]         #
#---------------------------------------#
discord-chat-module: false
channel-chat-id: ''

# command
command-chat-change-arg: 'channel'
minecraft-chat-arg: 'mc'
discord-chat-arg: 'dc'
channel-change-message: 'The channel has been changed to: {CHANNEL}'

# minecraft server chat
discord-prefix: '&d[DC] '
mc-prefix: '&a[MC] '
message-mark: '&7: '
message-color: '&7'
nick-color: '&f'

# discord channel chat
discord-message-mark: ': '

# embeds chat colors
discord-user-rgb:
  - 142
  - 87
  - 178

mc-user-rgb:
  - 33
  - 241
  - 99

#---------------------------------------#
#        [discord-console-module]       #
#---------------------------------------#

discord-console-module: false
channel-console-id: ''

discord-console-commands: true

block-error-messages: false

#---------------------------------------#
#         [discord-info-module]         #
#---------------------------------------#
discord-info-module: false
channel-info-id: ''

# message info reload time in seconds, min time: 20s (for safe)
message-reload-time: 20

discord-info-rgb:
  - 26
  - 154
  - 74

# Placeholders
# {SERVER_ONLINE}, {SERVER_MAX_PLAYERS}, {SERVER_TIME}, {SERVER_ALL_PLAYERS}, {SERVER_WORLDS}, {SERVER_VERSION},
# {SERVER_ALLOW_NETHER}, {SERVER_ALLOW_END}
embed-tittle: ''
embed-desc: ''
embed-info:
  - 'Online://{SERVER_ONLINE}/{SERVER_MAX_PLAYERS}'
  - 'Up Time:// {SERVER_TIME}'
  - 'All Players:// {SERVER_ALL_PLAYERS}'
  - 'Worlds:// {SERVER_WORLDS}'
  - 'Ver:// {SERVER_VERSION}'
  - 'Nether:// {SERVER_ALLOW_NETHER}'
  - 'End:// {SERVER_ALLOW_END}'

false-info: 'fal'
true-info: 'tru'