#DiscordMc by Norbit4
#Ver 1.0.1

#bot config
#bot token: https://discord.com/developers/applications
token: ''
channel-name: ''
bot-activity: ''

#minecraft server chat
discord-prefix: '&d[Discord] '
mc-prefix: '&a[Mc] '
message-color: '&7'
nick-color: '&f'
message-mark: '&7:'
