#---------------------------------------#
# DiscordMc by Norbit4
# ver 1.2.2
# github: https://github.com/Norbit4

#---------------------------------------#
#             [bot config]              #
#---------------------------------------#

# configuration: https://github.com/Norbit4/DiscordMc/wiki/Configuration
enable: false
prefix-command: 'discordmc'
sync-command-arg: 'sync'
sync-command-clear-arg: 'syncclear'
bot-token: ''
bot-activity: ''
discord-server-id: ''

# types: local/mysql/mongodb
database-type: 'local'
host: ''
port: 3306
user: ''
password: ''
database: ''
ssl: false

embed-profile-title: 'Profile'

embed-profile:
  # 'TITLE//DESC'
  - 'nick://{NICK}'
  - 'user:// {USER}'
  - 'status:// {STATUS}'
  - 'world:// {WORLD}'
  - 'loc:// X: {X} Y: {Y} Z: {Z}'
  - 'namemc:// {NAME_MC}'

# discord rank sync
sync-rank-enable: false
# discord name sync (set discord user mc name)
# this option need enabled 'sync-rank-enabled'
# nick sync does not work for the discord server owner, it is specific to discord servers!
sync-name: false

# wiki sync roles: https://github.com/Norbit4/DiscordMc/wiki/Rank-sync
sync-roles:
  - 'rank-permission:discord-rank-id'

namemc-non-premium: 'Player is non-premium'
player-offline-status: 'offline'
player-online-status: 'online'
user-in-not-sync: 'You are not synchronized! Use **/sync** to sync your accounts!'
arg-user-in-not-sync: 'This user is not synchronized!'
embed-profile-rgb:
  - 154
  - 199
  - 50

#---------------------------------------#
#              [messages]               #
#---------------------------------------#

# discord embeds colors
warn-message-tittle: 'WARN'
warn-message-rgb:
  #R
  - 213
  #G
  - 156
  #B
  - 71

success-message-tittle: 'SUCCESS'
success-message-rgb:
  - 26
  - 154
  - 74

error-message-tittle: 'ERROR'
error-message-rgb:
  - 194
  - 50
  - 50

#discord messages
player-is-sync: 'This player is synchronize!'
discord-user-is-sync: 'You are synchronized!'
offline-player: 'This player is offline!'
sync-info: 'Type **/{PREFIX} {ARG1}** in minecraft chat to sync your accounts!'
sync-success: 'The player **{PLAYER}** has been synchronized with **{DISCORD}** account!'

#minecraft messages
permission-message: '&cYou dont have permissions!'
sync-info-mc: '&7Type &8/&b{PREFIX} {ARG1} &7to connect your account with&a {DISCORD}'
sync-success-mc: '&aSuccess! &7The account has been synchronized with &c{DISCORD}!'
sync-clear-mc: '&aSuccess! &7The sync has been cleared!'
sync-time-out: '&7You dont have sync pending!'

wrong-args-message: '&7Use: &8/&b{PREFIX} &a{ARG1} &8<&a{ARG2}&8>'

command-args-list:
  - '&7------------&8[{PREFIX}&8]------------'
  - ''
  - '&8/&b{PREFIX} &a{SYNC_CMD} &7- accept sync accounts'
  - '&8/&b{PREFIX} &a{SYNC_CLEAR_CMD} &7- clear your sync'
  - '&8/&b{PREFIX} &a{CHANNEL_CMD} &8<&a{CHANNEL_MC_ARG}/{CHANNEL_DC_ARG}&8> &7- change chat channel'
  - '&8/&b{PREFIX} &arankreload &7- reload synced rank'
  - '&8/&b{PREFIX} &areload &7- reload config.yml'
  - ''

#---------------------------------------#
#         [discord-chat-module]         #
#---------------------------------------#
# help: https://github.com/Norbit4/DiscordMc/wiki/Chat-module

discord-chat-module: false
channel-chat-id: ''

# command
command-chat-change-arg: 'channel'
minecraft-chat-arg: 'mc'
discord-chat-arg: 'dc'
channel-change-message: '&7The channel has been changed to: &a{CHANNEL}'

# minecraft server chat
discord-prefix: '&d[DC] '
mc-prefix: '&a[MC] '
message-mark: '&7: '
message-color: '&7'
nick-color: '&f'

# discord channel chat
discord-message-mark: ': '

# embeds color
discord-user-rgb:
  - 142
  - 87
  - 178

mc-user-rgb:
  - 33
  - 241
  - 99

#---------------------------------------#
#        [discord-console-module]       #
#---------------------------------------#
# help: https://github:com/Norbit4/DiscordMc/wiki/Cosole-module

discord-console-module: false
channel-console-id: ''

#allowed commands in discord console
discord-console-commands: true

#allowed to display info discord console
discord-console-display: true

block-error-messages: false

# blocked commands in discord console
blocked-commands:
  - help
  - pl

#---------------------------------------#
#         [discord-info-module]         #
#---------------------------------------#
# help: https://github.com/Norbit4/DiscordMc/wiki/Info-module

discord-info-module: false
channel-info-id: ''

# message info reload time in seconds, min time: 20s (for safe)
message-reload-time: 30

discord-info-rgb:
  - 26
  - 154
  - 74

# folders ignored when creating worlds list
ignore-folders:
  - 'cache'
  - 'plugins'
  - 'logs'
  - 'crash-reports'
  - 'libraries'
  - 'config'
  - 'versions'

# Placeholders:
# {SERVER_ONLINE}, {SERVER_MAX_PLAYERS}, {SERVER_TIME}, {SERVER_ALL_PLAYERS}, {SERVER_WORLDS}, {SERVER_VERSION},
# {SERVER_ALLOW_NETHER}, {SERVER_ALLOW_END}
embed-tittle: ''
embed-desc: ''
embed-info:
  # 'TITLE//DESC'
  - 'Online://{SERVER_ONLINE}/{SERVER_MAX_PLAYERS}'
  - 'Up Time:// {SERVER_TIME}'
  - 'All Players:// {SERVER_ALL_PLAYERS}'
  - 'Worlds:// {SERVER_WORLDS}'
  - 'Ver:// {SERVER_VERSION}'
  - 'Nether:// {SERVER_ALLOW_NETHER}'
  - 'End:// {SERVER_ALLOW_END}'

false-info: 'false'
true-info: 'true'