#DiscordMc by Norbit4
#Ver 1.0.1
#
#Bot token: https://discord.com/developers/applications
token: ''
#Chat channel name in discord
channelname: ''
botactivity: ''
discordprefix: '&d[Discord]'
mcprefix: '&a[Mc]'
