package pl.norbit.discordmc.server.config;

public class PluginConfig {

    public static String CHAT_CHANNEL_ID, DISCORD_PREFIX, TOKEN, MC_PREFIX, BOT_ACTIVITY, NICK_COLOR, MESSAGE_COLOR,
            MESSAGE_MARK, DISCORD_MESSAGE_MARK, COMMAND_PREFIX, MONGO_HOST, MONGO_PASS, MONGO_USER, MONGO_DATABASE,
            PLAYER_IS_SYNC_DC, OFFLINE_PLAYER_DC, SYNC_INFO_DC, SYNC_SUCCESS_DC, SYNC_INFO_MC, SYNC_SUCCESS_MC,
            SYNC_TIME_OUT, SUCCESS_TITTLE, WARN_TITTLE, ERROR_TITTLE, SERVER_ID, CONSOLE_CHANNEL_ID;

    public static boolean PLUGIN_ENABLE, MONGO_SSL, CHAT_MODULE, CONSOLE_MODULE, DISCORD_CONSOLE_COMMANDS,
            BLOCK_WARN_MESSAGES, BLOCK_ERROR_MESSAGES;

    public static int EMBED_DISCORD_R, EMBED_DISCORD_G, EMBED_DISCORD_B, EMBED_MC_R, EMBED_MC_G, EMBED_MC_B, MONGO_PORT,
            EMBED_ERROR_R, EMBED_ERROR_G, EMBED_ERROR_B, EMBED_WARN_R, EMBED_WARN_G, EMBED_WARN_B, EMBED_SUCCESS_R,
            EMBED_SUCCESS_G, EMBED_SUCCESS_B;
}

