package pl.norbit.discordmc.server.config;

public class PluginConfig {
    public static String CHANNEL_NAME, DISCORD_PREFIX, TOKEN, MC_PREFIX, BOT_ACTIVITY, NICK_COLOR, MESSAGE_COLOR, MESSAGE_MARK,
            DISCORD_MESSAGE_MARK, COMMAND_PREFIX, MONGO_HOST, MONGO_PASS, MONGO_USER, MONGO_DATABASE;
    public static boolean CHAT_MODULE, PLUGIN_ENABLE, MONGO_PORT;
    public static int EMBED_DISCORD_R, EMBED_DISCORD_G, EMBED_DISCORD_B, EMBED_MC_R, EMBED_MC_G, EMBED_MC_B;
}

